---
- name: Ensure dir init.groovy.d exists
  file:
    path: /var/lib/jenkins/init.groovy.d
    owner: jenkins
    group: jenkins
    state: directory
    mode: '0755'

- name: Disable jenkins setup daemon UpgradeWizard file
  copy:
    content: '2.50'
    dest: /var/lib/jenkins/jenkins.install.UpgradeWizard.state
    mode: '0644'
    owner: jenkins
    group: jenkins
  notify:
    - Restart Jenkins

- name: Disable jenkins setup daemon InstallUtil file
  copy:
    content: '2.50'
    dest: /var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion
    mode: '0644'
    owner: jenkins
    group: jenkins
  notify:
    - Restart Jenkins

- name: Create configuration for jenkins admin user
  template:
    src: basic-security.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
    mode: '0644'
    owner: jenkins
    group: jenkins
  notify:
    - Restart Jenkins

- name: Run all handlers registered until now
  meta: flush_handlers

- name: Wait for Jenkins to start up before installing plugins.
  shell: "curl -D - --silent --max-time 5 http://localhost:8080/cli/"
  register: result
  until: (result.stdout.find("403 Forbidden") != -1) or (result.stdout.find("200 OK") != -1) and (result.stdout.find("Please wait while") == -1)
  retries: "5"
  delay: "20"
  changed_when: false
  always_run: yes

- name: Install Jenkins plugins
  shell: "/usr/bin/java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080/ install-plugin greenballs git job-dsl workflow-aggregator --username jenkins --password jenkins -restart"

- name: Create configuration for web_pipe job
  template:
    src: pipeline.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/pipeline.groovy
    mode: '0644'
    owner: jenkins
    group: jenkins
  notify:
    - Restart Jenkins