---
- name: Add Jenkins repo key
  apt_key:
    url: "https://pkg.jenkins.io/debian/jenkins.io.key "
    state: present
- name: Add Jenkins repo
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian binary/ #https disabled / apt cacher ng issues
    state: present
- name: Install latest Jenkins
  apt:
    name: jenkins
    state: latest
  notify:
    - Enable Jenkins
    - Start Jenkins
  
