Vagrant.configure("2") do |config|
    config.vm.box = "ub1604"
    config.vm.network "public_network", bridge: "Microsoft Loopback Adapter"
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.gui = true
    end

    #config.vm.provision :shell, :inline => 'echo \'Acquire::http::Proxy "http://172.30.30.2:3142";\' > /etc/apt/apt.conf.d/02proxy' 

    config.vm.provision :shell, :inline => 'apt-get update && apt-get install -y puppet'
    config.vm.provision :shell, :inline => 'puppet module install puppetlabs-apt'

    config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "puppet/manifests"
        puppet.module_path = "puppet/modules"
        puppet.options = ['--verbose']
    end


end
