Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"

    config.vm.define "lb" do |machine|
        machine.vm.network "public_network", ip: "172.30.30.200", bridge: "Microsoft Loopback Adapter"
        machine.vm.hostname = "lb"
        machine.vm.synced_folder ".", "/vagrant", disabled: true
        machine.vm.provider "virtualbox" do |v|
            v.memory = 256
            v.cpus = 1
        end

        machine.vm.provision :shell, :inline => 'echo \'Acquire::http::Proxy "http://172.30.30.2:3142";\' > /etc/apt/apt.conf.d/02proxy'
    end

    config.vm.define "web1" do |machine|
        machine.vm.network "public_network", ip: "172.30.30.201", bridge: "Microsoft Loopback Adapter"
        machine.vm.hostname = "web1"
        machine.vm.synced_folder ".", "/vagrant", disabled: true
        machine.vm.provider "virtualbox" do |v|
            v.memory = 256
            v.cpus = 1
        end

        machine.vm.provision :shell, :inline => 'echo \'Acquire::http::Proxy "http://172.30.30.2:3142";\' > /etc/apt/apt.conf.d/02proxy'
    end

    config.vm.define "web2" do |machine|
        machine.vm.network "public_network", ip: "172.30.30.202", bridge: "Microsoft Loopback Adapter"
        machine.vm.hostname = "web2"
        machine.vm.synced_folder ".", "/vagrant", disabled: true
        machine.vm.provider "virtualbox" do |v|
            v.memory = 256
            v.cpus = 1
        end

        machine.vm.provision :shell, :inline => 'echo \'Acquire::http::Proxy "http://172.30.30.2:3142";\' > /etc/apt/apt.conf.d/02proxy'
    end

    config.vm.define 'controller', primary: true do |machine|
        machine.vm.network "public_network", ip: "172.30.30.30", bridge: "Microsoft Loopback Adapter"
        machine.vm.hostname = "controller"
        machine.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=700"] #ansible was complaining about key permissions

        machine.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
        end

        machine.vm.provision :shell, :inline => 'echo \'Acquire::http::Proxy "http://172.30.30.2:3142";\' > /etc/apt/apt.conf.d/02proxy'

        machine.vm.provision :ansible_local do |ansible|
            ansible.provisioning_path = "/vagrant/ansible"
            ansible.playbook       = "playbook.yml"
            ansible.verbose        = false
            ansible.limit          = "all"
            ansible.inventory_path = "inventory"
        end
    end
end
