# Define bridge loopback network
BRIDGE_NET="172.30.30."

servers=[
    {
        :hostname => "lb",
        :ip => BRIDGE_NET + "200",
        :box => "ubuntu/xenial64",
        :ram => 256,
        :cpu => 1,
        :disable_synced_folder => true
    },
    {
        :hostname => "web1",
        :ip => BRIDGE_NET + "201",
        :box => "ubuntu/xenial64",
        :ram => 256,
        :cpu => 1,
        :disable_synced_folder => true
    },        
    {
        :hostname => "web2",
        :ip => BRIDGE_NET + "202",
        :box => "ubuntu/xenial64",
        :ram => 256,
        :cpu => 1,
        :disable_synced_folder => true
    },
    {
        :hostname => "controller",
        :ip => BRIDGE_NET + "30",
        :box => "ubuntu/xenial64",
        :ram => 1024,
        :cpu => 1,
        :disable_synced_folder => false,
        :run_ansible_local => true
    },
]

Vagrant.configure("2") do |config|

    servers.each do |server|
        config.vm.define server[:hostname] do |machine|
            machine.vm.box = server[:box]
            machine.vm.hostname = server[:hostname]
            machine.vm.network "public_network", ip: server[:ip], bridge: "Microsoft Loopback Adapter"


            if server[:disable_synced_folder]
                machine.vm.synced_folder ".", "/vagrant", disabled: true
            else
                machine.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=700"] #ansible was complaining about key permissions
            end

            machine.vm.provider "virtualbox" do |v|
                v.memory = server[:ram]
                v.cpus = server[:cpu]
            end

            machine.vm.provision :shell, :inline => 'echo \'Acquire::http::Proxy "http://172.30.30.2:3142";\' > /etc/apt/apt.conf.d/02proxy'

            if server[:run_ansible_local]
                machine.vm.provision :ansible_local do |ansible|
                    ansible.provisioning_path = "/vagrant/ansible"
                    ansible.playbook       = "playbook.yml"
                    ansible.verbose        = false
                    ansible.limit          = "all"
                    ansible.inventory_path = "inventory"
                end
            end
        end
    end
end
