---
- name: Add git group
  group:
    name: git
    state: present

- name: Add git user
  user:
    name: git
    group: git
    shell: /usr/bin/git-shell
    state: present

- name: Generate ssh key for jenkins user
  user: 
    name: jenkins
    generate_ssh_key: yes
    state: present

- name: Ensure dir /repo exists
  file:
    path: /repo
    owner: git
    group: git
    state: directory
    mode: '2755'

- name: Read jenkins user pub key
  slurp:
    src: /var/lib/jenkins/.ssh/id_rsa.pub
  register: jenkins_pub

- name: Grant jenkins user access to git
  authorized_key:
    user: git
    state: present
    key: "{{ jenkins_pub['content'] | b64decode }}"

- name: add localhost to known_hosts - user jenkins
  shell: 'ssh-keyscan localhost > ~/.ssh/known_hosts'
  become_user: jenkins

- name: Check /repo/dev.git already exists  
  stat: path=/repo/dev.git
  register: dev_bare_repo

- block:
  - name: Creating dev git repository
    shell: "git init --bare /repo/dev.git"

  - name: Updating repo permissions
    file: 
      path: /repo/dev.git
      recurse: yes
      owner: git

  - name: Ensure pipeline job hook exists
    template:
      src: post-receive.j2
      dest: /repo/dev.git/hooks/post-receive
      owner: git
      group: git
      mode: '0755'
  when: dev_bare_repo.stat.isdir is not defined

### 
### Adding a user for use by development and
### Simulating user action for commiting files to repo
###

- name: Ensure git group exists
  group:
    name: development
    state: present

- name: Ensure git user exists
  user:
    name: dev1
    group: development
    password: '$6$FgOGQsaP$U2qZLAulMu9CnFFPxgldA7vuD6B1pcpJZdMINO45/Gjua3wcG6jA0HkZTtxOxzgqyvvA8/iJgWTwQQ1HO2hbY/'
    generate_ssh_key: yes
    state: present

- name: Read dev1 user pub key
  slurp:
    src: /home/dev1/.ssh/id_rsa.pub
  register: dev1_pub

- name: Grant dev1 user access to git
  authorized_key:
    user: git
    state: present
    key: "{{ dev1_pub['content'] | b64decode }}"

- name: add localhost to known_hosts - user dev1
  shell: 'ssh-keyscan localhost > ~/.ssh/known_hosts'
  become_user: dev1

- name: Check /home/dev1/dev already exists  
  stat: path=/home/dev1/dev
  register: dev_checkout

- block:
  - name: Checkout the bare repo
    git:
      repo: ssh://git@localhost:/repo/dev.git
      dest: /home/dev1/dev
      accept_hostkey: yes
    become_user: dev1
    ignore_errors: true
    register: output

  - name: Check the error from git module
    fail: msg="{{ output.msg }}"
    when: "'Failed to checkout branch master' not in output.msg"


  - name: Ensure dir /home/dev1/dev/web exists
    file:
      path: /home/dev1/dev/web
      owner: dev1
      group: development
      state: directory
      mode: '0755'

  - name: Copy repo files for first commit
    copy:
      directory_mode: yes
      src: dev/
      dest: /home/dev1/dev
      owner: dev1
      group: development

  - name: Commit basic files to the repo
    shell: 'cd /home/dev1/dev && git config --global user.name "Dev One" && git add . && git commit -m "First commit" && git push'
    become_user: dev1
  when: dev_checkout.stat.isdir is not defined


