---
- hosts: all
  gather_facts: False
  pre_tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (apt update && apt install -y python-minimal)
    changed_when: False
  - setup: # aka gather_facts
  roles:
    - warcry
    - use_apt_proxy
  become: yes
    
- hosts: lb
  roles:
    - nginx_install
    - nginx_configure
  become: yes

- hosts: web
  roles:
    - simple_webserver
  become: yes

- hosts: controller
  roles:
    - jenkins_install
    - jenkins_configure
  become: yes